<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Menu;
use Illuminate\Support\Facades\Schema;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        $menus = [
            [
                'id' => 1,
                'title' => 'Home',
                'url' => '/',
                'page_id' => null,
                'parent_id' => null,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-11-22 06:44:21',
            ],
            [
                'id' => 2,
                'title' => 'About',
                'url' => null,
                'page_id' => 22,
                'parent_id' => null,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-12-29 12:02:15',
            ],
            [
                'id' => 3,
                'title' => 'Academic',
                'url' => null,
                'page_id' => 25,
                'parent_id' => null,
                'order' => 3,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-12-29 14:37:57',
            ],
            [
                'id' => 4,
                'title' => 'Administration',
                'url' => null,
                'page_id' => 23,
                'parent_id' => null,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-12-29 14:15:37',
            ],
            [
                'id' => 5,
                'title' => 'Notice',
                'url' => 'http://barishal.test/notices',
                'page_id' => null,
                'parent_id' => null,
                'order' => 10,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-12-09 14:39:16',
            ],
            [
                'id' => 6,
                'title' => 'Admission',
                'url' => null,
                'page_id' => 27,
                'parent_id' => null,
                'order' => 6,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-12-29 14:57:05',
            ],
            [
                'id' => 8,
                'title' => 'Co-Curriculam',
                'url' => null,
                'page_id' => 37,
                'parent_id' => null,
                'order' => 8,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-12-29 18:02:53',
            ],
            [
                'id' => 9,
                'title' => 'Facilities',
                'url' => null,
                'page_id' => 32,
                'parent_id' => null,
                'order' => 9,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-12-29 17:27:19',
            ],
            [
                'id' => 11,
                'title' => 'Login',
                'url' => '/admin',
                'page_id' => null,
                'parent_id' => null,
                'order' => 11,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-11-22 06:44:21',
                'updated_at' => '2025-11-22 06:44:21',
            ],
            [
                'id' => 33,
                'title' => 'Link BG',
                'url' => null,
                'page_id' => 12,
                'parent_id' => null,
                'order' => 10,
                'is_active' => 0,
                'is_highlighted' => 1,
                'highlight_color' => '#ff0000',
                'created_at' => '2025-12-17 06:33:24',
                'updated_at' => '2025-12-29 11:54:33',
            ],
            [
                'id' => 34,
                'title' => 'Gallery',
                'url' => '#',
                'page_id' => null,
                'parent_id' => null,
                'order' => 10,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-17 07:19:27',
                'updated_at' => '2025-12-17 07:20:26',
            ],
            [
                'id' => 35,
                'title' => 'Photo Gallery',
                'url' => '/gallery',
                'page_id' => null,
                'parent_id' => 34,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-17 07:21:20',
                'updated_at' => '2025-12-29 16:57:17',
            ],
            [
                'id' => 36,
                'title' => 'Video Gallery',
                'url' => 'http://barishal.test/video-gallery',
                'page_id' => null,
                'parent_id' => 34,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-17 07:22:47',
                'updated_at' => '2025-12-17 07:22:47',
            ],
            [
                'id' => 37,
                'title' => 'At a Glance',
                'url' => null,
                'page_id' => 20,
                'parent_id' => 2,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 11:58:44',
                'updated_at' => '2025-12-29 11:58:44',
            ],
            [
                'id' => 38,
                'title' => 'History',
                'url' => null,
                'page_id' => 21,
                'parent_id' => 2,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 12:00:45',
                'updated_at' => '2025-12-29 12:00:45',
            ],
            [
                'id' => 39,
                'title' => 'Why study RCESC',
                'url' => null,
                'page_id' => 22,
                'parent_id' => 2,
                'order' => 3,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 12:02:37',
                'updated_at' => '2025-12-29 12:02:37',
            ],
            [
                'id' => 40,
                'title' => 'Message of Chief Patron',
                'url' => 'https://demo.mosconicuplive.com/message/chief-patron-massage',
                'page_id' => null,
                'parent_id' => 4,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 12:04:58',
                'updated_at' => '2025-12-29 12:04:58',
            ],
            [
                'id' => 41,
                'title' => 'Message of the Chairman',
                'url' => 'https://demo.mosconicuplive.com/message/brig-gen-md-solmon-ibne-a-rouf',
                'page_id' => null,
                'parent_id' => 4,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 12:08:17',
                'updated_at' => '2025-12-29 12:08:17',
            ],
            [
                'id' => 42,
                'title' => 'Message of Principal',
                'url' => 'https://demo.mosconicuplive.com/message/lt-col-mohammad-sharif-uzzaman',
                'page_id' => null,
                'parent_id' => 4,
                'order' => 3,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 12:08:57',
                'updated_at' => '2025-12-29 12:08:57',
            ],
            [
                'id' => 43,
                'title' => 'Teacher & Staff',
                'url' => 'https://s3.trusteduerp.xyz/op/teacher?insId=1018',
                'page_id' => null,
                'parent_id' => 4,
                'order' => 3,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 12:11:13',
                'updated_at' => '2025-12-29 12:11:13',
            ],
            [
                'id' => 44,
                'title' => 'Governing Body',
                'url' => null,
                'page_id' => 23,
                'parent_id' => 4,
                'order' => 0,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 13:24:52',
                'updated_at' => '2025-12-29 13:24:52',
            ],
            [
                'id' => 45,
                'title' => 'Syllabus',
                'url' => null,
                'page_id' => 24,
                'parent_id' => 3,
                'order' => 0,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 14:34:38',
                'updated_at' => '2025-12-29 14:34:38',
            ],
            [
                'id' => 46,
                'title' => 'Class Routine',
                'url' => '#',
                'page_id' => null,
                'parent_id' => 3,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 14:35:28',
                'updated_at' => '2025-12-29 14:35:28',
            ],
            [
                'id' => 47,
                'title' => 'Academic calendar',
                'url' => null,
                'page_id' => 25,
                'parent_id' => 3,
                'order' => 3,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 14:38:53',
                'updated_at' => '2025-12-29 14:38:53',
            ],
            [
                'id' => 48,
                'title' => 'Admission Circular',
                'url' => null,
                'page_id' => null,
                'parent_id' => 6,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 14:54:07',
                'updated_at' => '2025-12-29 14:55:55',
            ],
            [
                'id' => 49,
                'title' => 'Prospectus',
                'url' => null,
                'page_id' => 27,
                'parent_id' => 6,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 14:57:26',
                'updated_at' => '2025-12-29 14:57:26',
            ],
            [
                'id' => 50,
                'title' => 'Online Admission',
                'url' => '#',
                'page_id' => null,
                'parent_id' => 6,
                'order' => 0,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 14:58:20',
                'updated_at' => '2025-12-29 14:58:20',
            ],
            [
                'id' => 51,
                'title' => 'Library',
                'url' => 'https://s3.trusteduerp.xyz/st/login?insId=1018',
                'page_id' => null,
                'parent_id' => null,
                'order' => 10,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 16:40:30',
                'updated_at' => '2025-12-29 16:44:44',
            ],
            [
                'id' => 52,
                'title' => 'School Library',
                'url' => 'https://s3.trusteduerp.xyz/op/library?insId=1018',
                'page_id' => null,
                'parent_id' => 51,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 16:42:05',
                'updated_at' => '2025-12-29 16:42:05',
            ],
            [
                'id' => 53,
                'title' => 'Online Fee',
                'url' => '#',
                'page_id' => null,
                'parent_id' => null,
                'order' => 9,
                'is_active' => 1,
                'is_highlighted' => 1,
                'highlight_color' => '#dc3545',
                'created_at' => '2025-12-29 16:43:20',
                'updated_at' => '2025-12-29 16:50:12',
            ],
            [
                'id' => 55,
                'title' => 'Multimedia Class Room',
                'url' => null,
                'page_id' => 28,
                'parent_id' => 9,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:27:40',
                'updated_at' => '2025-12-29 17:27:40',
            ],
            [
                'id' => 56,
                'title' => 'Indoor Game',
                'url' => null,
                'page_id' => 29,
                'parent_id' => 9,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:27:53',
                'updated_at' => '2025-12-29 17:27:53',
            ],
            [
                'id' => 57,
                'title' => 'Outdoor Games',
                'url' => null,
                'page_id' => 30,
                'parent_id' => 9,
                'order' => 3,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:28:08',
                'updated_at' => '2025-12-29 17:28:08',
            ],
            [
                'id' => 58,
                'title' => 'Library',
                'url' => null,
                'page_id' => 31,
                'parent_id' => 9,
                'order' => 4,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:28:23',
                'updated_at' => '2025-12-29 17:28:23',
            ],
            [
                'id' => 59,
                'title' => 'Science Lab',
                'url' => null,
                'page_id' => 32,
                'parent_id' => 9,
                'order' => 5,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:28:39',
                'updated_at' => '2025-12-29 17:28:39',
            ],
            [
                'id' => 60,
                'title' => 'Language Club',
                'url' => null,
                'page_id' => 33,
                'parent_id' => 8,
                'order' => 1,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:31:53',
                'updated_at' => '2025-12-29 17:31:53',
            ],
            [
                'id' => 61,
                'title' => 'Debate Club',
                'url' => null,
                'page_id' => 34,
                'parent_id' => 8,
                'order' => 2,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:54:40',
                'updated_at' => '2025-12-29 17:54:40',
            ],
            [
                'id' => 62,
                'title' => 'GK and Current Affairs',
                'url' => null,
                'page_id' => 35,
                'parent_id' => 8,
                'order' => 3,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 17:56:20',
                'updated_at' => '2025-12-29 17:56:20',
            ],
            [
                'id' => 63,
                'title' => 'Quranic Club',
                'url' => null,
                'page_id' => 36,
                'parent_id' => 8,
                'order' => 4,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 18:03:19',
                'updated_at' => '2025-12-29 18:03:19',
            ],
            [
                'id' => 64,
                'title' => 'Calligraphy and arts and crafts Society',
                'url' => null,
                'page_id' => 37,
                'parent_id' => 8,
                'order' => 5,
                'is_active' => 1,
                'is_highlighted' => 0,
                'highlight_color' => null,
                'created_at' => '2025-12-29 18:03:33',
                'updated_at' => '2025-12-29 18:03:33',
            ],
        ];

        foreach ($menus as $menu) {
            Menu::updateOrCreate(['id' => $menu['id']], $menu);
        }

        Schema::enableForeignKeyConstraints();
    }
}
